version: '3.4'

services:
  db:
    image: mysql:latest
    container_name: MySQL
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=maindb
      - MYSQL_USER=SeanWoo
      - MYSQL_PASSWORD=88003535555
  booststreamserver:
    image: booststreamserver:release
    container_name: BoostStreamServer
    build:
      context: .
      dockerfile: BoostStreamServer/Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - 5080:5080